export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;
export const MAX_BATCH_SIZE = 100; // Match backend limit
export const FREE_TIER_MAX_TARGET_LANGUAGES = 2;
const PRO_TIER_MAX_TARGET_LANGUAGES = 5;
const BUSINESS_TIER_MAX_TARGET_LANGUAGES = 26;
const FREE_TIER_MAX_CONCURRENT_BATCHES = 1;
const PRO_TIER_MAX_CONCURRENT_BATCHES = 3;
const BUSINESS_TIER_MAX_CONCURRENT_BATCHES = 5;
const ENTERPRISE_TIER_MAX_CONCURRENT_BATCHES = 20;

const TARGET_LANGUAGES_BY_TIER: Record<string, number> = {
  free: FREE_TIER_MAX_TARGET_LANGUAGES,
  pro: PRO_TIER_MAX_TARGET_LANGUAGES,
  business: BUSINESS_TIER_MAX_TARGET_LANGUAGES,
  enterprise: BUSINESS_TIER_MAX_TARGET_LANGUAGES,
};

const CONCURRENT_BATCHES_BY_TIER: Record<string, number> = {
  free: FREE_TIER_MAX_CONCURRENT_BATCHES,
  pro: PRO_TIER_MAX_CONCURRENT_BATCHES,
  business: BUSINESS_TIER_MAX_CONCURRENT_BATCHES,
  enterprise: ENTERPRISE_TIER_MAX_CONCURRENT_BATCHES,
};

export function getMaxTargetLanguages(tier: string): number {
  return TARGET_LANGUAGES_BY_TIER[tier] ?? FREE_TIER_MAX_TARGET_LANGUAGES;
}

export function getMaxConcurrentBatches(tier: string): number {
  return CONCURRENT_BATCHES_BY_TIER[tier] ?? FREE_TIER_MAX_CONCURRENT_BATCHES;
}
